[project]
name = "swastha-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.115.6",
]

[dependency-groups]
dev = [
    "ruff>=0.8.2",
]

[tool.ruff.lint]
extend-select = ["E", "W"]
